### ISSUE TITLE
sth about rectGrasp -> evaluation

### ISSUE THREAD

**Issue by cww97** [graspnet/graspnetAPI#10]
I have successfully get rect grasps from here, does these 7-d rect grasp the same as what you explained above?

further more, I wanna evaluate these grasps, can I use convert from here, and then use evaluation from here?

**Comment by cww97** [comment]
I have successfully get rect grasps from [here](https://github.com/graspnet/rectangle-graspnet-multiObject-multiGrasp/blob/master/grasp_multiObject_multiGrasp/tools/predict_graspRGD.py), does these 7-d rect grasp the same as what you explained above?

further more, I wanna evaluate these grasps, can I use convert from [here](https://graspnetapi.readthedocs.io/en/latest/example_convert.html#convert-rectangle-format-to-6d-format), and then use evaluation from [here](https://graspnetapi.readthedocs.io/en/latest/example_eval.html)?

**Comment by GouMinghao** [comment]
Yes, you are right
