### ISSUE TITLE
What method/tool do you use to get a complete point cloud of a single object?

### ISSUE THREAD

**Issue by Ctiger96** [graspnet/graspnetAPI#13]
Hi,

I want to make the pointcloud for single object of my own dataset but I don't know how to make the pointcloud complete and proper. I have tried [https://github.com/F2Wang/ObjectDatasetTools](url), but I find that it doesn't work well on the object who has complex shape.
So, would you please give me some advice or share your tool/method of making the pointcloud for a single object? Thx!
BTW, would you please publish the purchase link of the new objects you added in the graspnet? Thx!

Hope to hear from you soon.

**Comment by Fang-Haoshu** [comment]
Hi! We used a commercial 3D scanner from  shining3d: https://www.shining3d.cn/solutions/einscan-sp/
I will organize the link this afternoon.

Best wishes

**Comment by Ctiger96** [comment]
THX!

**Comment by Fang-Haoshu** [comment]
Hi， the object purchase link is available on this page now: https://graspnet.net/datasets.html
