### ISSUE TITLE
I have read the graspnet evaluation part (grasp annotated data generation), and the grasp generation part is using DEXNET. I am wondering if it can be changed to graspnet-baseline when the my model (trained) is mature later.

### ISSUE THREAD

**Issue by gzchenjiajun** [graspnet/graspnetAPI#15]
I have read the graspnet  evaluation  part (grasp   annotated data generation), and the grasp  generation part is using DEXNET. I am wondering if it can be changed to graspnet-baseline when the my model (trained) is mature later.
Feasible?

**Comment by gzchenjiajun** [comment]
"For each image, we densely annotate 6-DoF grasp poses by analytic computation of force closure [29]."
Is gripper generation based on [29]? [29] Do you have the relevant information?
I don't see it in the Graspnet Repo

**Comment by GouMinghao** [comment]
There is a little confusion that the dexnet pretrained network was not used to generate our label. Instead, we share the same metric in assigning labels with dexnet.
