### ISSUE TITLE
Question about the to_rect_grasp_group function

### ISSUE THREAD

**Issue by DrawZeroPoint** [graspnet/graspnetAPI#16]
Hi,
First thanks for sharing this great work. I noticed that in the to_rect_grasp_group function, the line:

https://github.com/graspnet/graspnetAPI/blob/f312d7e2a73ca97f9e791cf3f1ab3aeacebac3e9/graspnetAPI/grasp.py#L519

seems to preventing certain Grasp from converting to RectGrasp. I wonder want exactly the mask does and why the filter is needed.

**Comment by Fang-Haoshu** [comment]
Rect grasp only works for the grasps that are verticle to the images. Thus we need this filter
