### ISSUE TITLE
How gripper-specific are the pre-trained weights?

### ISSUE THREAD

**Issue by clemense** [graspnet/graspnetAPI#18]
Hello,
I'm trying to understand what aspects of the gripper geometry are encoded in the trained network weights;  under which circumstances would I need to retrain given a different parallel jaw gripper (assuming the gripper is parameterized by finger length/depth and maximum width [i.e. the joint limit of the prismatic finger joints]) ?

In your [figure](https://raw.githubusercontent.com/graspnet/graspnetAPI/master/grasp_definition.png)
![image](https://user-images.githubusercontent.com/1800546/109396382-11b7c700-78e6-11eb-8df9-d5036d5c6793.png)

there is an "2 cm" distance and I'm unsure what this refers to. Is this the distance of the frame origin to the physical palm of the gripper?

Or put differently: How do I match the grasp frame from a different gripper to be able to re-use the trained weights?

Thanks!

**Comment by Fang-Haoshu** [comment]
Hi, yes, the 2cm is the distance of the frame origin to the physical palm of the gripper.

To match the grasp frame from a different gripper, we have tried a simple calibration step which works well:
1.  put a cube on the table
2. run the [demo.py](https://github.com/graspnet/graspnet-baseline/blob/main/demo.py) and check the visualized output
3. execute the robot grasp and stop the robot at the grasp pose, compare it with the visualized grasp in step 2. If there are any offset, reduce them from the camera-gripper frame calibration configuration.

The visualized grasp in step 2 is exactly what the network would expect. Thus you can utilize it. In most cases, retrain the model is not necessary.

Best
