### ISSUE TITLE
in grasp_eval, when k+1 > len(score_list)

### ISSUE THREAD

**Issue by cww97** [graspnet/graspnetAPI#20]
https://github.com/graspnet/graspnetAPI/blob/master/graspnetAPI/graspnet_eval.py#L195
```
                    if k+1 > len(score_list):
                        grasp_accuracy[k,fric_idx] = np.sum(((score_list<=fric) & (score_list>0)).astype(int))/(k+1)
```
why the denominator here is `(k+1)` instead of the length of score_list, or should this grids removed from `grasp_accuracy`

**Comment by GouMinghao** [comment]
Thanks for your question, The denominator is ```(k+1)``` because we require the algorithm to output at least ```k``` grasp poses.  
This line has the same result with adding several zero-score grasp poses until there are ```k``` grasp poses.
