### ISSUE TITLE
Question about rectgrasp dataset

### ISSUE THREAD

**Issue by June-Jo** [graspnet/graspnetAPI#21]
Thanks for your grasp dataset. 
I have a question about rect grasp dataset.

Rect grasp dataset contains some rect grasp data that its center point is outside the target object like the driver and the yellow round fruits of below picture.

Are they some error data generated by the process from 3d to 2d?

How can deal with them?

![example](https://user-images.githubusercontent.com/24308201/115329261-089ff380-a1cd-11eb-9a29-3fe063060d4d.PNG)

**Comment by Fang-Haoshu** [comment]
Hi, the key is at this line: https://github.com/graspnet/graspnetAPI/blob/master/graspnetAPI/grasp.py#L519
We choose 3d grasp that is align with z-axis in 0.99 threshold, where 0.99 is the cosine value of the grasp approach direction with the z-axis.
You can either make it stricter, or enlarge the grasp width.

**Comment by June-Jo** [comment]
@Fang-Haoshu Thanks for your help! I can deal with it now. :)
