### ISSUE TITLE
suction 1 billion

### ISSUE THREAD

**Issue by trungpham2606** [graspnet/graspnetAPI#22]
Dear @GouMinghao @Fang-Haoshu @cww97 @chenxi-wang,
I have read your work on suctionnet 1 billion, the link in the paper led me here but I did not see the code for generating suction dataset.

**Comment by Fang-Haoshu** [comment]
Hi, thanks for your interest!

The related code will be available at this organization(https://github.com/graspnet) after the paper is accepted. Please stay tuned:D

**Comment by trungpham2606** [comment]
@Fang-Haoshu 
Excuse me, but in suction part, what if there's a hole between vi and vi+1 or maybe inside the perimeter of suction gripper.
As the image bellow:
![image](https://user-images.githubusercontent.com/35657426/116024214-ec420200-a677-11eb-95fd-4ff2175e4323.png)

In those cases, the suction must be invalid but according to the seal and wrench condition, there maybe still the pose.

**Comment by PDementevna** [comment]
Dear @Fang-Haoshu, any updates on publication? I'm just wondering about having a look at the code😃

**Comment by trungpham2606** [comment]
@PDementevna 
I'm also looking forward to the code but it has been a long time :((

**Comment by Fang-Haoshu** [comment]
@intrepidChw
