### ISSUE TITLE
关于rect标注中score的疑问

### ISSUE THREAD

**Issue by Puppet097** [graspnet/graspnetAPI#23]
[https://github.com/graspnet/rectangle-graspnet-multiObject-multiGrasp/issues/10](url)
请问为什么从rect标注文件中通过score筛选可行抓取在API中和multigrasp数据处理中是截然相反的？

**Comment by GouMinghao** [comment]
This bug has been addressed in version 1.2.10. Thanks for you bug report!  
https://github.com/graspnet/graspnetAPI/commit/335617e6aa966b1444a6a1675f648fd8b147515d
