### ISSUE TITLE
对数据集中的部分不懂之处

### ISSUE THREAD

**Issue by JingKangSun** [graspnet/graspnetAPI#26]
作者您好：

      感谢你们提供的数据集！但在使用你们的数据集的过程中，我有三个不解之处：

       第一，在你们的数据集中，每个场景有256个不同的视角，每个视角下都有对物体6D姿态的标注信息，为‘pos_in_world'和'ori_in_world',我的理解是：这表示物体在世界坐标系下的6D姿态。
       困惑的地方在于，**对于同一个场景的不同视角，物体在世界坐标系下的姿态是没有发生变化的，那么为什么不同视角下相同物体对应的‘pos_in_world'和'ori_in_world是不同的**？

       第二，collision_label中对每个物体上的n个点上的不同抓取是否发生碰撞进行了标注，请问抓取是否碰撞是根据在单个目标的点云中，夹爪在闭合前是否与点云发生碰撞决定的吗？将物体堆叠到一起的时候，杂乱场景中夹爪是否发生碰撞又是如何确定的？

       第三，在最终得到的抓取姿势中，[scores, widths, heights, depths, rotations, target_points, object_ids]，其中rotations表示旋转矩阵，target_points表示平移向量吗？那么depth是用来干什么的?根据你们的文章，我对depth理解是其表示对抓取目标点沿逼近方向的逼近距离，按照这种理解，平移向量是不是要由target_points和depth共同得出？

      期待您的回答！

      谢谢！

**Comment by Fang-Haoshu** [comment]
你好！
1. ‘pos_in_world'和'ori_in_world'表示相机视角下的pose
2. collision_label会把全部物体放到场景里再做检测
3. 你说的没错，平移向量要由target_points和depth共同得出

**Comment by quanfeifan** [comment]
您好，请问您的第三个问题理解了吗？我对于平移向量如何计算一头雾水，请指教
