### ISSUE TITLE
Rect Label: Score

### ISSUE THREAD

**Issue by MicheleOliva** [graspnet/graspnetAPI#27]
Hi everyone.
I'm trying to understand the meaning of the "score" label in the rect_labels. In this API's code I have the impression that the meaning of this variable is the same as the 6DOF Grasp but in the repo [
rectangle-graspnet-multiObject-multiGrasp](https://github.com/graspnet/rectangle-graspnet-multiObject-multiGrasp) the authors treats this variable as the row_score: `mask = grasp[:, 5] < 0.2`.
Can someone explain to me which score the variable refers to?

**Comment by Fang-Haoshu** [comment]
Hi! It is a bug in the repo. We used old data in our own server. For all the released data, the score means 1-fric_coef, which means that higher is better.
