### ISSUE TITLE
Reproducing results of GGCNN on GraspNet

### ISSUE THREAD

**Issue by Merlyy** [graspnet/graspnetAPI#30]
Hello,
i am trying to reproduce your results with GGCNN on GraspNet and i am having a few questions:

1. In your paper you wrote you used the official implementation of GGCNN (i asume your mean [this one](https://github.com/dougsm/ggcnn)). How exactly did you handle the amount of labeld grasps? Converting the grasps to the needed maps for quality, angle and width takes far too much time with the original code.
2. After training a GGCNN on the train data of GraspNet and evaluating the estimated grasp poses i only achieve a AP of ~3% (for now only trying on the seen split). Can you provide weights or code for your training of these models?

I really want to work with your evaluation pipeline as i find it a really nice way of evaluating grasp estimation methods without having to physically executing every grasp. 

Thank you for your work and help.

**Comment by Fang-Haoshu** [comment]
Hi, thanks for your interest and recognitions of our evaluation benchmark. For the grasp label, you can start with our generated 'Rectangle Grasp Labels' at https://graspnet.net/datasets.html. The generation is indeed computation expensive. The rectangle labels need one to two weeks' computation on our servers with hundreds of CPU threads. For the ggcnn models, it is no longer maintained as we strongly recommend using the model with better performance at: https://github.com/graspnet/graspnet-baseline

Best

**Comment by Merlyy** [comment]
Thank you for your quick response.
It does not necessarily have to be GGCNN, but the class of models which estimate the grasp poses on a pixel level, that are of interest to me (such as [GRConvNet](https://github.com/skumra/robotic-grasping)).

I am already using your generated labels of rectangle grasps and converting them to the needed label format (images) myself. I assume the common way of labeling all pixels within the inner third of the grasp rectangle with the parameters of the respective grasp does not work well enough.
I tried recovering the grasps from the labels generated in that way with your rectangle grasps, but these are often bad grasps as they can be far away of the original grasp.

So to specify: How did you convert your rectangle grasps to the needed format of maps for quality, angle and width too be able to train models such as GGCNN on your data?

**Comment by Fang-Haoshu** [comment]
Hi,  the inner third of the grasp rectangle is not suitable because our generated grasp is not centered. The original process requires a pose nms and a centering process on point cloud. With the rectangle dataset, a workaround is to use inner 1/10 as positive, outer gripper area as negative(unless overlapped with other positive areas) and the remaining area as ignore loss region.

**Comment by Merlyy** [comment]
Thank you for that information.

On another note: I just used the generated rectangle grasp labels and ran them trough the evaluation. The resulting AP on seen objects was 7%. Did you do any postproccessing on the estimated rectangle grasps to achieve ~16% as stated in your paper?

**Comment by Fang-Haoshu** [comment]
Hi, do you mean directly using the data for evaluation or using the model trained on the data?

**Comment by Merlyy** [comment]
I used the rectangle grasps supplied. No training or model involved.

Here is the code i used:
```python
def gt_predictor(graspnet_eval: GraspNetEval,
                 scene_id: int, anno_id: int,
                 camera:str = 'kinect'):
    """Fuction acting as predictor using the ground truth labels.
    Usefull for sanity checking the labels.
    """
    grasps = graspnet_eval.loadGrasp(scene_id, anno_id, format='rect', camera=camera)

    # remove grasps at the image borders
    # comparison with shape - 1 because 719.9 gets rounded to 720
    idxs = np.argwhere(grasps.center_points[:, 0] >= 1279)
    grasps.remove(idxs)

    idxs = np.argwhere(grasps.center_points[:, 1] >= 719)
    grasps.remove(idxs)

    depth = graspnet_eval.loadDepth(scene_id, camera, anno_id)
    return grasps.to_grasp_group(camera, depth)
```
The resulting grasps were saved so exam_eval.py could be used.

**Comment by Fang-Haoshu** [comment]
Oh I see, seems 7% is too low and makes no sense. We need to look into that. 
For evaluation, collision detection is needed.

**Comment by Merlyy** [comment]
Can you please clarify what you mean by "collision detection is needed"? Do you mean grasps which are in collision should be ignored when computing AP?

**Comment by Fang-Haoshu** [comment]
Hi, yes. You should filter out the grasps that will collide with the point cloud before evaluation, since you will also not choose them for robot execution.

**Comment by Merlyy** [comment]
> Hi, the inner third of the grasp rectangle is not suitable because our generated grasp is not centered. The original process requires a pose nms and a centering process on point cloud. With the rectangle dataset, a workaround is to use inner 1/10 as positive, outer gripper area as negative(unless overlapped with other positive areas) and the remaining area as ignore loss region.

Do you have a reference for this approach or was this an original idea of yours?

**Comment by Fang-Haoshu** [comment]
Hi, it's a suggestion of mine.
