### ISSUE TITLE
Difference between uploaded rect labels and projected 6d labels

### ISSUE THREAD

**Issue by Merlyy** [graspnet/graspnetAPI#33]
While working with your [uploaded rect labels](https://graspnet.net/datasets.html) i noticed labels with negative center coordinates for the realsense.
While trying to find the cause i noticed that the uploaded label files contain far more rect grasps than you get when projecting the 6d labels with the `to_rect_grasp_group()` function.

Can you please explain how the uploaded labels where generated and how to use them?

**Comment by GouMinghao** [comment]
The uploaded rect labels is generated by running [this file](https://github.com/graspnet/graspnetAPI/blob/master/examples/exam_generate_rectangle_grasp.py). However, a minor bug is witnessed in https://github.com/graspnet/graspnetAPI/pull/32 . We will upload the modified version very soon.

**Comment by Fang-Haoshu** [comment]
The uploaded labels are updated on the website. Seems some boxes are eliminated.
