### ISSUE TITLE
Missing close.jpg in mtl for object 68

### ISSUE THREAD

**Issue by Jiayuan-Gu** [graspnet/graspnetAPI#34]
Hi. I download the object models from Google Drive, and find that `textured.obj.mtl` uses `close.jpg`, which is not included. Could anyone help fix it? Thanks.

**Comment by Fang-Haoshu** [comment]
Hi, I guess it is not a bug. I remember that some objects missed the close.jpg due to some reasons. But it does not affect the usage of the dataset.

**Comment by Fang-Haoshu** [comment]
If you meet any further problem when using the dataset, feel free to open an issue again.
