### ISSUE TITLE
loadGrasp method does not return best grasps

### ISSUE THREAD

**Issue by paolotron** [graspnet/graspnetAPI#39]
The method [https://github.com/graspnet/graspnetAPI/blob/ca350fcce8663b197cd7b50f41d7087b6b08f65a/graspnetAPI/graspnet.py#L634](loadGrasp) throws out all the grasps that have a friction coefficient of 0, grasps with friction coefficient of 0 should be the best ones.

**Comment by chenxi-wang** [comment]
Hi, the friction coefficients are discretized in 10 classes (0.1, 0.2, ..., 1.0). Grasps with friction coefficient 0.1 are the best ones.
