### ISSUE TITLE
关于GraspGroup部分的疑问

### ISSUE THREAD

**Issue by bjutlss** [graspnet/graspnetAPI#44]
你好，首先很感谢你的工作。
在使用过程中，`gg = GraspGroup(preds)`来生成抓取，我尝试遍历`gg`中的元素打印对应的`object_id`，结果全都是`-1`。我想知道如何获取每个抓取姿态对应的`object_id`类别信息。
我想要确定场景中每个物体对应的抓取姿态，以确保抓取特定的物体，而不是得分最高的抓取。

**Comment by Fang-Haoshu** [comment]
您好，preds里是网络预测的部分，应该没有object_id，我忘了当时gt里面有没有载入obj id了。如果是做特定物体的抓取，我们建议采用grasp tracking抓取跟踪的方法或者用mask tracking，可以参考我们anygrasp里的实现方式。
