### ISSUE TITLE
About the evaluation: how to apply different friction?

### ISSUE THREAD

**Issue by Johnson1207** [graspnet/graspnetAPI#45]
Hi, I'm a master student also work on the grasp generation.
I appreciate your efforts very much, it actually save alot of times for me.

To compare the performace like the ways in your papers , I have to compare the result in different friction.
But after browsering the code of this API, I still don't know where to adjust the friction _u_.
Please helps.

**Comment by chenxi-wang** [comment]
Hi, you can modify the friction efficient [here](https://github.com/graspnet/graspnetAPI/blob/master/graspnetAPI/utils/eval_utils.py#L363).

**Comment by Johnson1207** [comment]
Thanks for reply.
So if I want to evaluate the result of AP_0.8, I should set  `fc_list = np.array([0.8, 0.6, 0.4, 0.2])`, right?

**Comment by chenxi-wang** [comment]
Sure. If you do not need the average from 0.8 to 0.2, you can just set `fc_list = np.array([0.8])`.

**Comment by Johnson1207** [comment]
Got it, Thanks!
