### ISSUE TITLE
您好，请问grasp_nms文件和nms_grasp方法有给出吗

### ISSUE THREAD

**Issue by biosbeta** [graspnet/graspnetAPI#53]
nms抓取非极大值抑制的具体实现在项目文件中未找到    
def nms(self, translation_thresh = 0.03, rotation_thresh = 30.0 / 180.0 * np.pi):
        '''
        **Input:**

        - translation_thresh: float of the translation threshold.

        - rotation_thresh: float of the rotation threshold.

        **Output:**

        - GraspGroup instance after nms.
        '''
        from grasp_nms import nms_grasp
        return GraspGroup(nms_grasp(self.grasp_group_array, translation_thresh, rotation_thresh))

**Comment by andyoung009** [comment]
你好，请问您找到了相关的文件吗？grasp_nms似乎是一个单独的安装包文件，我也没有发现其python代码。

**Comment by lqy668honor** [comment]
请问解决了吗？我发现了这个问题。
