### ISSUE TITLE
whats then meaning of each number of rect grasp label

### ISSUE THREAD

**Issue by cww97** [graspnet/graspnetAPI#9]

**Comment by Fang-Haoshu** [comment]
Hi, should be (score, width, height, depth, rotation, translation, object_id), where object id is set to -1 by default(not used)

**Comment by gachiemchiep** [comment]
Hello @Fang-Haoshu 
I understand the meaning of score, rotation, translation, object_id. 
Would you mind explain the meaning of width, height, depth. 
Is the width equal to "6", height equal to "7" and depth equal to "4" as in this picture.  

![gripper](https://user-images.githubusercontent.com/2300329/103858780-47b5a780-50fc-11eb-8691-8c1321677fee.jpg)

**Comment by Fang-Haoshu** [comment]
![grasp_definition](https://user-images.githubusercontent.com/12446953/103863041-15f01100-50fb-11eb-8df9-8c670829924a.png)
Hi, it is like this one

**Comment by cww97** [comment]
I have successfully get rect grasps from [here](https://github.com/graspnet/rectangle-graspnet-multiObject-multiGrasp/blob/master/grasp_multiObject_multiGrasp/tools/predict_graspRGD.py), does these 7-d rect grasp the same as what you explained above?

further more, I wanna evaluate these grasps, can I use convert from [here](https://graspnetapi.readthedocs.io/en/latest/example_convert.html#convert-rectangle-format-to-6d-format), and then use evaluation from [here](https://graspnetapi.readthedocs.io/en/latest/example_eval.html)?

**Comment by gachiemchiep** [comment]
@Fang-Haoshu 
Sorry, I still don't understand those values. 
For example, if we detected a grasp pose like this image :
https://github.com/atenpas/gpd/blob/master/readme/hand_frame.png 
For now, I understand the meaning of each variable like this: 
1. score: the confidence of detected grasp 
2.  rotation: rotation matrix of detected grasp 
3.  translation: position (3d coordinates) where grasp is detected
4.  object_id
5. width, height, depth: I guess that is the size of cube that contains gripper
